CC='gcc'
CPP='gcc -E'
CXX='g++'
GREP='/bin/grep'
have_bunzip2=yes
have_gunzip=yes
have_tar=yes
have_make=yes
have_patch=yes
XML2_CONFIG='/usr/bin/xml2-config'
XSLT_CONFIG='/usr/bin/xslt-config'
HAVE_LIBZ=yes
HAVE_LIBJPEG=yes
HAVE_LIBSSL=yes
HAVE_SSL2=no
HAVE_LIBREADLINE=yes
